# Generated by Django 5.1.2 on 2025-01-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='icon',
            field=models.CharField(default='fitness', max_length=100, verbose_name='Article Type Icon'),
        ),
    ]
