# Generated by Django 5.1.2 on 2025-01-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='order',
            new_name='service',
        ),
    ]
